/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/cisco-sso/snapshotpolicy/pkg/apis/snapshotpolicy/v1alpha1"
	scheme "github.com/cisco-sso/snapshotpolicy/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// SnapshotPoliciesGetter has a method to return a SnapshotPolicyInterface.
// A group's client should implement this interface.
type SnapshotPoliciesGetter interface {
	SnapshotPolicies(namespace string) SnapshotPolicyInterface
}

// SnapshotPolicyInterface has methods to work with SnapshotPolicy resources.
type SnapshotPolicyInterface interface {
	Create(*v1alpha1.SnapshotPolicy) (*v1alpha1.SnapshotPolicy, error)
	Update(*v1alpha1.SnapshotPolicy) (*v1alpha1.SnapshotPolicy, error)
	UpdateStatus(*v1alpha1.SnapshotPolicy) (*v1alpha1.SnapshotPolicy, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.SnapshotPolicy, error)
	List(opts v1.ListOptions) (*v1alpha1.SnapshotPolicyList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.SnapshotPolicy, err error)
	SnapshotPolicyExpansion
}

// snapshotPolicies implements SnapshotPolicyInterface
type snapshotPolicies struct {
	client rest.Interface
	ns     string
}

// newSnapshotPolicies returns a SnapshotPolicies
func newSnapshotPolicies(c *SnapshotpolicyV1alpha1Client, namespace string) *snapshotPolicies {
	return &snapshotPolicies{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the snapshotPolicy, and returns the corresponding snapshotPolicy object, and an error if there is any.
func (c *snapshotPolicies) Get(name string, options v1.GetOptions) (result *v1alpha1.SnapshotPolicy, err error) {
	result = &v1alpha1.SnapshotPolicy{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("snapshotpolicies").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of SnapshotPolicies that match those selectors.
func (c *snapshotPolicies) List(opts v1.ListOptions) (result *v1alpha1.SnapshotPolicyList, err error) {
	result = &v1alpha1.SnapshotPolicyList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("snapshotpolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested snapshotPolicies.
func (c *snapshotPolicies) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("snapshotpolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a snapshotPolicy and creates it.  Returns the server's representation of the snapshotPolicy, and an error, if there is any.
func (c *snapshotPolicies) Create(snapshotPolicy *v1alpha1.SnapshotPolicy) (result *v1alpha1.SnapshotPolicy, err error) {
	result = &v1alpha1.SnapshotPolicy{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("snapshotpolicies").
		Body(snapshotPolicy).
		Do().
		Into(result)
	return
}

// Update takes the representation of a snapshotPolicy and updates it. Returns the server's representation of the snapshotPolicy, and an error, if there is any.
func (c *snapshotPolicies) Update(snapshotPolicy *v1alpha1.SnapshotPolicy) (result *v1alpha1.SnapshotPolicy, err error) {
	result = &v1alpha1.SnapshotPolicy{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("snapshotpolicies").
		Name(snapshotPolicy.Name).
		Body(snapshotPolicy).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *snapshotPolicies) UpdateStatus(snapshotPolicy *v1alpha1.SnapshotPolicy) (result *v1alpha1.SnapshotPolicy, err error) {
	result = &v1alpha1.SnapshotPolicy{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("snapshotpolicies").
		Name(snapshotPolicy.Name).
		SubResource("status").
		Body(snapshotPolicy).
		Do().
		Into(result)
	return
}

// Delete takes name of the snapshotPolicy and deletes it. Returns an error if one occurs.
func (c *snapshotPolicies) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("snapshotpolicies").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *snapshotPolicies) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("snapshotpolicies").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched snapshotPolicy.
func (c *snapshotPolicies) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.SnapshotPolicy, err error) {
	result = &v1alpha1.SnapshotPolicy{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("snapshotpolicies").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
