/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	snapshotpolicyv1alpha1 "github.com/cisco-sso/snapshotpolicy/pkg/apis/snapshotpolicy/v1alpha1"
	versioned "github.com/cisco-sso/snapshotpolicy/pkg/client/clientset/versioned"
	internalinterfaces "github.com/cisco-sso/snapshotpolicy/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/cisco-sso/snapshotpolicy/pkg/client/listers/snapshotpolicy/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// SnapshotPolicyInformer provides access to a shared informer and lister for
// SnapshotPolicies.
type SnapshotPolicyInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.SnapshotPolicyLister
}

type snapshotPolicyInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewSnapshotPolicyInformer constructs a new informer for SnapshotPolicy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewSnapshotPolicyInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredSnapshotPolicyInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredSnapshotPolicyInformer constructs a new informer for SnapshotPolicy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredSnapshotPolicyInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SnapshotpolicyV1alpha1().SnapshotPolicies(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SnapshotpolicyV1alpha1().SnapshotPolicies(namespace).Watch(options)
			},
		},
		&snapshotpolicyv1alpha1.SnapshotPolicy{},
		resyncPeriod,
		indexers,
	)
}

func (f *snapshotPolicyInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredSnapshotPolicyInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *snapshotPolicyInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&snapshotpolicyv1alpha1.SnapshotPolicy{}, f.defaultInformer)
}

func (f *snapshotPolicyInformer) Lister() v1alpha1.SnapshotPolicyLister {
	return v1alpha1.NewSnapshotPolicyLister(f.Informer().GetIndexer())
}
