/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/cisco-sso/snapshotpolicy/pkg/apis/snapshotpolicy/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// SnapshotPolicyLister helps list SnapshotPolicies.
type SnapshotPolicyLister interface {
	// List lists all SnapshotPolicies in the indexer.
	List(selector labels.Selector) (ret []*v1alpha1.SnapshotPolicy, err error)
	// SnapshotPolicies returns an object that can list and get SnapshotPolicies.
	SnapshotPolicies(namespace string) SnapshotPolicyNamespaceLister
	SnapshotPolicyListerExpansion
}

// snapshotPolicyLister implements the SnapshotPolicyLister interface.
type snapshotPolicyLister struct {
	indexer cache.Indexer
}

// NewSnapshotPolicyLister returns a new SnapshotPolicyLister.
func NewSnapshotPolicyLister(indexer cache.Indexer) SnapshotPolicyLister {
	return &snapshotPolicyLister{indexer: indexer}
}

// List lists all SnapshotPolicies in the indexer.
func (s *snapshotPolicyLister) List(selector labels.Selector) (ret []*v1alpha1.SnapshotPolicy, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.SnapshotPolicy))
	})
	return ret, err
}

// SnapshotPolicies returns an object that can list and get SnapshotPolicies.
func (s *snapshotPolicyLister) SnapshotPolicies(namespace string) SnapshotPolicyNamespaceLister {
	return snapshotPolicyNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// SnapshotPolicyNamespaceLister helps list and get SnapshotPolicies.
type SnapshotPolicyNamespaceLister interface {
	// List lists all SnapshotPolicies in the indexer for a given namespace.
	List(selector labels.Selector) (ret []*v1alpha1.SnapshotPolicy, err error)
	// Get retrieves the SnapshotPolicy from the indexer for a given namespace and name.
	Get(name string) (*v1alpha1.SnapshotPolicy, error)
	SnapshotPolicyNamespaceListerExpansion
}

// snapshotPolicyNamespaceLister implements the SnapshotPolicyNamespaceLister
// interface.
type snapshotPolicyNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all SnapshotPolicies in the indexer for a given namespace.
func (s snapshotPolicyNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.SnapshotPolicy, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.SnapshotPolicy))
	})
	return ret, err
}

// Get retrieves the SnapshotPolicy from the indexer for a given namespace and name.
func (s snapshotPolicyNamespaceLister) Get(name string) (*v1alpha1.SnapshotPolicy, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("snapshotpolicy"), name)
	}
	return obj.(*v1alpha1.SnapshotPolicy), nil
}
