/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/cisco-sso/snapshotpolicy/pkg/apis/snapshotpolicy/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSnapshotPolicies implements SnapshotPolicyInterface
type FakeSnapshotPolicies struct {
	Fake *FakeSnapshotpolicyV1alpha1
	ns   string
}

var snapshotpoliciesResource = schema.GroupVersionResource{Group: "snapshotpolicy.ciscosso.io", Version: "v1alpha1", Resource: "snapshotpolicies"}

var snapshotpoliciesKind = schema.GroupVersionKind{Group: "snapshotpolicy.ciscosso.io", Version: "v1alpha1", Kind: "SnapshotPolicy"}

// Get takes name of the snapshotPolicy, and returns the corresponding snapshotPolicy object, and an error if there is any.
func (c *FakeSnapshotPolicies) Get(name string, options v1.GetOptions) (result *v1alpha1.SnapshotPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(snapshotpoliciesResource, c.ns, name), &v1alpha1.SnapshotPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SnapshotPolicy), err
}

// List takes label and field selectors, and returns the list of SnapshotPolicies that match those selectors.
func (c *FakeSnapshotPolicies) List(opts v1.ListOptions) (result *v1alpha1.SnapshotPolicyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(snapshotpoliciesResource, snapshotpoliciesKind, c.ns, opts), &v1alpha1.SnapshotPolicyList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.SnapshotPolicyList{ListMeta: obj.(*v1alpha1.SnapshotPolicyList).ListMeta}
	for _, item := range obj.(*v1alpha1.SnapshotPolicyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested snapshotPolicies.
func (c *FakeSnapshotPolicies) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(snapshotpoliciesResource, c.ns, opts))

}

// Create takes the representation of a snapshotPolicy and creates it.  Returns the server's representation of the snapshotPolicy, and an error, if there is any.
func (c *FakeSnapshotPolicies) Create(snapshotPolicy *v1alpha1.SnapshotPolicy) (result *v1alpha1.SnapshotPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(snapshotpoliciesResource, c.ns, snapshotPolicy), &v1alpha1.SnapshotPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SnapshotPolicy), err
}

// Update takes the representation of a snapshotPolicy and updates it. Returns the server's representation of the snapshotPolicy, and an error, if there is any.
func (c *FakeSnapshotPolicies) Update(snapshotPolicy *v1alpha1.SnapshotPolicy) (result *v1alpha1.SnapshotPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(snapshotpoliciesResource, c.ns, snapshotPolicy), &v1alpha1.SnapshotPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SnapshotPolicy), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeSnapshotPolicies) UpdateStatus(snapshotPolicy *v1alpha1.SnapshotPolicy) (*v1alpha1.SnapshotPolicy, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(snapshotpoliciesResource, "status", c.ns, snapshotPolicy), &v1alpha1.SnapshotPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SnapshotPolicy), err
}

// Delete takes name of the snapshotPolicy and deletes it. Returns an error if one occurs.
func (c *FakeSnapshotPolicies) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(snapshotpoliciesResource, c.ns, name), &v1alpha1.SnapshotPolicy{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSnapshotPolicies) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(snapshotpoliciesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.SnapshotPolicyList{})
	return err
}

// Patch applies the patch and returns the patched snapshotPolicy.
func (c *FakeSnapshotPolicies) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.SnapshotPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(snapshotpoliciesResource, c.ns, name, data, subresources...), &v1alpha1.SnapshotPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SnapshotPolicy), err
}
